version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_HOST: "${DB_HOSTNAME}"
    restart: always
      
  app:
    container_name: app
    build: ./chewie-back
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./chewie-back:/chewie-back
    env_file: .env
    working_dir: /chewie-back

  # front:
  #   container_name: front
  #   image: node
  #   ports:
  #       - "${FRONT_PORT}:${FRONT_PORT}"
  #   depends_on:
  #       - app
  #   volumes:
  #       - ./chewie-front:/chewie-front
  #   working_dir: /chewie-front
  #   command: bash -c "yarn && yarn start"